/**
 * @qos/core — manifest.ts
 *
 * MessageManifest type definition, builder, and signature verifier.
 * The manifest is the "message envelope" stored server-side — it contains
 * only metadata (no plaintext, no raw AES key). The actual message content
 * lives on IPFS; the AES key is wrapped with the recipient's public key.
 *
 * Canonical signing spec (deterministic, covers CID order):
 *   sig_input = sender_id + recipient_id + String(timestamp) + cids.join(",") + wrappedKeyB64
 *   hash      = SHA-256(sig_input)     [handled inside ECDSA sign()]
 *   signature = ECDSA_sign(hash, sender_private_key)  // base64-encoded
 */

import { sign, verify } from './keys.js';
import type { WrappedKey } from './keys.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MessageManifest {
  /** UUID — generated by the server on receipt, echoed back to the client. */
  id: string;
  /** Sender's internal UUID (matches users.id in the DB). */
  sender_id: string;
  /** Recipient's internal UUID. */
  recipient_id: string;
  /**
   * Ordered list of IPFS CIDs for the encrypted fragments.
   * Order is the canonical source of truth for reassembly.
   * Any reordering is detected by signature verification.
   */
  cids: string[];
  /** AES message key wrapped with recipient's ECDH public key (see keys.ts). */
  wrapped_key: WrappedKey;
  /** Unix millisecond timestamp set at send time. Also the TTL anchor. */
  timestamp: number;
  /** timestamp + 7 days in Unix ms — manifests are deleted after this point. */
  expires_at: number;
  /**
   * ECDSA P-256 signature of the canonical input string (base64).
   * Covers: sender_id, recipient_id, timestamp, cids (ordered), wrapped_key.wrappedKeyB64
   */
  signature: string;
}

/** Partial manifest — all fields except id, expires_at, and signature (which are computed). */
export interface ManifestInput {
  sender_id: string;
  recipient_id: string;
  cids: string[];
  wrapped_key: WrappedKey;
  timestamp?: number; // defaults to Date.now()
}

const TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days in ms

// ---------------------------------------------------------------------------
// Canonical input builder
// ---------------------------------------------------------------------------

/**
 * Build the canonical string that is signed/verified.
 * Deterministic regardless of JSON field ordering.
 */
function canonicalInput(
  sender_id: string,
  recipient_id: string,
  timestamp: number,
  cids: string[],
  wrappedKeyB64: string,
): string {
  return sender_id + recipient_id + String(timestamp) + cids.join(',') + wrappedKeyB64;
}

// ---------------------------------------------------------------------------
// Build a manifest (signing happens here)
// ---------------------------------------------------------------------------

/**
 * Build and sign a MessageManifest.
 *
 * The `id` field is a placeholder UUID until the server assigns a real one
 * on receipt. The caller may update it after the server responds.
 */
export async function buildManifest(
  input: ManifestInput,
  senderPrivateKey: CryptoKey,
): Promise<MessageManifest> {
  const timestamp = input.timestamp ?? Date.now();
  const expires_at = timestamp + TTL_MS;

  const canonical = canonicalInput(
    input.sender_id,
    input.recipient_id,
    timestamp,
    input.cids,
    input.wrapped_key.wrappedKeyB64,
  );

  const signature = await sign(canonical, senderPrivateKey);

  return {
    id: crypto.randomUUID(),  // placeholder; server will overwrite
    sender_id: input.sender_id,
    recipient_id: input.recipient_id,
    cids: input.cids,
    wrapped_key: input.wrapped_key,
    timestamp,
    expires_at,
    signature,
  };
}

// ---------------------------------------------------------------------------
// Verify a manifest signature
// ---------------------------------------------------------------------------

/**
 * Verify the manifest's ECDSA signature.
 * Returns `true` if the signature is valid; `false` otherwise.
 *
 * Called by the recipient after fetching the manifest from the API server.
 * A `false` return means the manifest was tampered with (server-side or in-transit).
 */
export async function verifyManifest(
  manifest: MessageManifest,
  senderPublicKey: CryptoKey,
): Promise<boolean> {
  const canonical = canonicalInput(
    manifest.sender_id,
    manifest.recipient_id,
    manifest.timestamp,
    manifest.cids,
    manifest.wrapped_key.wrappedKeyB64,
  );

  return verify(canonical, manifest.signature, senderPublicKey);
}
